# Project: ExamenFinalConstru
# Makefile created by Dev-C++ 5.4.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Administrador.o Operario.o Peon.o Empleado.o Asignacion.o Proyecto.o
LINKOBJ  = main.o Administrador.o Operario.o Peon.o Empleado.o Asignacion.o Proyecto.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
BIN      = ExamenFinalConstru.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Administrador.o: Administrador.cpp
	$(CPP) -c Administrador.cpp -o Administrador.o $(CXXFLAGS)

Operario.o: Operario.cpp
	$(CPP) -c Operario.cpp -o Operario.o $(CXXFLAGS)

Peon.o: Peon.cpp
	$(CPP) -c Peon.cpp -o Peon.o $(CXXFLAGS)

Empleado.o: Empleado.cpp
	$(CPP) -c Empleado.cpp -o Empleado.o $(CXXFLAGS)

Asignacion.o: Asignacion.cpp
	$(CPP) -c Asignacion.cpp -o Asignacion.o $(CXXFLAGS)

Proyecto.o: Proyecto.cpp
	$(CPP) -c Proyecto.cpp -o Proyecto.o $(CXXFLAGS)
